/// Builds the profile QR payload for a username.
///
/// This string is *not* an OS deep link — Connecta no longer registers a
/// `connecta://profile/...` handler. It is only ever encoded into a QR code
/// and decoded in-app by [QrScannerScreen], which parses the username out of
/// it and looks the profile up directly. Kept in this format for backwards
/// compatibility with QR codes generated by older builds.
String buildProfileLink(String username) => 'connecta://profile/$username';
